version: "3.9"
services:
  api:
    build: .
    env_file: .env
    environment:
      PYTHONPATH: /app        # 👈 add this
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      bash -lc "alembic upgrade head && gunicorn app.main:app
      -k uvicorn.workers.UvicornWorker
      --workers ${GUNICORN_WORKERS:-2}
      --bind 0.0.0.0:8000
      --timeout 120
      --keep-alive 5"
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: sparing
      MYSQL_USER: sparing
      MYSQL_PASSWORD: sparing
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode=""
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
  adminer:
    image: adminer:latest
    ports: ["8080:8080"]
    depends_on: [mysql]
